language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- grunt
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: S0D6lW9Nvjo1ag2XUxeSNhwWZXiT5ERf6/+zygiIgX9IQhgM3jHG8meplUJrDisvZ9kWZ8ccpWwPvGpTrgYzfbAulwvHff/6g0/vJyXgD5y+MtY3nQrKHrD4vrzslIZ22+YoV1Q0w3CmRkeAFU6/dLl/CzzPiFxSuD0dCOK9UcC1Tr6jOunVVRYAbcgaleb5dMktyDJ0GazjqW5H05YqLQRrcqAIF6cNT2+ndF1BIrrzB0UzZJAK0T3VeSd6xPM+qCM4hBoy7SxwhthgVLgOS9OGapdtFmq1NDky9aFTB3dt2VxzJxsgY/KNPvJxY2/oO2n8O0WubzvZD2WuUG/8ae5rgiTGiWlQTCQWBk+yAXptTQFRzLi5NFRIkQAOXwxwdyCWcgzE1PRdPsGTfyPE9RYlgJJ+t6ykBjed53ifQa2l+yl6xOG4GG0x55/SZTceWzvd7StUoWAQNHLcyEreep4358IsG4SfpGUvh0nHgYdav4er7OK3zEauAYK9cKBFrw52F7XIvUhlrE6hM54ymGPWtadKY90BLYDX7Yn6Z4ygKz9m5EpS/iLSIJr9QCIG8RKj+aPSBvgEBMBlEKPMzgQgS7BvEYytHEXrTbAA8apy/4ftQ6Kja/37dSOkbFSFxP1xFpcrmb67M1XcoepuoEL9lmyYI0iWgcr9oZI+9Yg=
  on:
    repo: kuzzleio/kuzzle-plugin-auth-github
    branch: master
