language: node_js
node_js:
- 6
before_script:
- npm install -g grunt-cli
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: W6RrogX5dypySLJo9E1ccVYk9PkpC7MPgjuuhn7knXtZ90q1ZfVfPFTP3vW3f6tbQWohBPbSSoKxzsgqlQSOlBX/RrIsGj4bU1FZi8+akiZzktZTO+smmE3TXRM3hGaKMc2sAPuAizcRhC+aFxT/WYQL3NR1ishhNQDpV8M+1KcOfENfoqPeqvv8/XjyjXf1Z9z95fwKV2OuyGX5hJyxINz48oPIQJLmg7XSdfXLykXKUT/jxmAprkaAPGnkQ60wsaNhupujOrmtwnMJM6c6hNPBewNGB3emz5QG7KA4yy9kmKo6whMnW36Fyz4XIbwtOxZ/qzkV9DZ3ITNwk5NcC1jTJrHBqRg8S+wjDPshRZWT3E9Ez9Fvz/vU5EkUIzoXf6gJE0RYN+KdmxH8KDGljq1iFVfu6kRNAN2bUdy36PQEWsnswJqLWIWkFKxtesU3exOFmOAEybbj/bG94topET4v8p9cBxZsWS0thXhUVwBC3UcDdQohNiwl3oTs9aTZGnCW1tdO6gT2sx1llTgO4P4g6KCpnmRiGSNjnM5x3TCMjJ6HTyiPrtTdH3Qa8fDAc60sDMtqZzjCXXAQtU+3zRQUQwQduoCcDZIzRBJ/pfR+cnmhe7iPmFgbwAONGZyMQiDQySjnS+4n209Wpz3xyUUqwt4sFYZ35v9/4qCozUM=
  on:
    repo: kuzzleio/kuzzle-plugin-auth-passport-oauth
    branch: master
