language: node_js
node_js:
- 6
before_script:
- npm install -g grunt-cli
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: PjqH5rNDdmNCVoXxJES0LSA3T+31n3u6YSazB4zFtT+gAQLpyioV6gtMmOCLBNPyUB3TVOP48654OU4dNYE52YjLLOF5ZAXLQhCUFqledB4aqAJywr931WxyLckULLn4G1Vjcjf5PvLU3HT7SE9rgd6oTzyE2WwjUT6fvXOd0Zbq6uYYgDGz2yS2hk+DiWUvzb7LE6EY14nt6z2rddp58hKR1GfIWQ5YJ7B/NT1H2dYWOAaj2R1N7DKHMM/1C79JbRTfSJFx4LltKiCzBQ+LIOmFF3/HIr2RLRyOHVdPyzRehEP4OH7buPz83QWhDUDPl8yiW8hJNq6K4RGS5UXiitiP11JGTHmDy72n0v2wzZ5EUcgBCs3s+Hi4Tlg0GA6NTaytxz0+HTR9EwypYuAq4z6o9RMfnYC+/lkLY0gTeU6peb7Db3AP0D133QbWKtwfT5BErhg9nSrJ9Pz0SriXNsssbNEMjA6Ff1Pe+5Z+KFVB26mfrN8IQdkxnt2Pl6GpLACQ3RafLDBaPjpVLR1q+TcELIxMRryM+1/SdaNpxysXu6gIcY1d3O3SuHocLdNGcJ/oSNzgutjiQNp2FSyr9EC5V1yf2AogoyQRGKFy+cW+sBl/mPlOq8P4RRsFXKMDG5kJxiWOkjQ/F8a41FcGzSaFDIfhU47hSG0EApoAFaw=
  on:
    repo: kuzzleio/kuzzle-plugin-auth-passport-oauth
    branch: master
