language: node_js
node_js:
- 6
before_script:
- npm install -g grunt-cli
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: Fi4ibDc9cTFajK5sLur053nJAC6WpXFJsDo4VVnKG6W2TmNkmv4MDE0x4eUMPVD5ps8wc7zNRsRpUwY5Dy+1MIJ5kNnn95KWseVpYrwD7zAI7i8p+Sw5NBkkBt9BYowBb4ILdruKJh48NnF/yR+YRBkH/aTX8FvKXtlN4S4vRm3iDpA0P/h9Bu0RiUASTTYTe5yqK/DwcJ3goX8vJOBpf3hF9Xz1VUlnNo1eA7fpHmnck09txXO835Aq7xenn9a9e5efx/5rqzpQOpNvR4uGQDuWuVtWoJVKJzNh/XOY/ETslneQKjdxospCGCnzSR8U7qEZ4X2/G1nWoteoh7z//HgNTrFpylt0CnBf3HWK3REqjplBRfc3/SDfnaQgK8lBgpzvzxVxbi8XNp3dR4mK/omfLIXHBQf+ABdNk8b5M5cMokPzEgMBTuaZCavuWlmDZtdVvzFYAqOzkpUieAQPDcrPzfPEq0G3Jont+tJmx7oHzKo/vLPmrDp8soYGlmP5OIuA/2bZRHFdkRc3sxJDnarqS0L6fGG2xaSWD4rs/iIdmh6EIpkvGWbiR3rmi8qWlodykagqWz8kWffozWOfxx5Ch3pUnVukRaJW87W2PWxLfUg0OrHIM/zFjI0g6xguJrLRAd14lIZsWIeHEJxX4G2WCZ0RyIb+ySUlsCp0Thg=
  on:
    repo: kuzzleio/kuzzle-plugin-auth-passport-oauth
    branch: master
